---

_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import ttest_ind

# Assignment 4 - Hypothesis Testing
This assignment requires more individual learning than previous assignments - you are encouraged to check out the [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/) to find functions or methods you might not have used yet, or ask questions on [Stack Overflow](http://stackoverflow.com/) and tag them as pandas and python related. And of course, the discussion forums are open for interaction with your peers and the course staff.

Definitions:
* A _quarter_ is a specific three month period, Q1 is January through March, Q2 is April through June, Q3 is July through September, Q4 is October through December.
* A _recession_ is defined as starting with two consecutive quarters of GDP decline, and ending with two consecutive quarters of GDP growth.
* A _recession bottom_ is the quarter within a recession which had the lowest GDP.
* A _university town_ is a city which has a high percentage of university students compared to the total population of the city.

**Hypothesis**: University towns have their mean housing prices less effected by recessions. Run a t-test to compare the ratio of the mean price of houses in university towns the quarter before the recession starts compared to the recession bottom. (`price_ratio=quarter_before_recession/recession_bottom`)

The following data files are available for this assignment:
* From the [Zillow research data site](http://www.zillow.com/research/data/) there is housing data for the United States. In particular the datafile for [all homes at a city level](http://files.zillowstatic.com/research/public/City/City_Zhvi_AllHomes.csv), ```City_Zhvi_AllHomes.csv```, has median home sale prices at a fine grained level.
* From the Wikipedia page on college towns is a list of [university towns in the United States](https://en.wikipedia.org/wiki/List_of_college_towns#College_towns_in_the_United_States) which has been copy and pasted into the file ```university_towns.txt```.
* From Bureau of Economic Analysis, US Department of Commerce, the [GDP over time](http://www.bea.gov/national/index.htm#gdp) of the United States in current dollars (use the chained value in 2009 dollars), in quarterly intervals, in the file ```gdplev.xls```. For this assignment, only look at GDP data from the first quarter of 2000 onward.

#Each function in this assignment below is worth 10%, with the exception of ```run_ttest()```, which is worth 50%.

In [2]:
# Use this dictionary to map state names to two letter acronyms
states = {'OH': 'Ohio', 'KY': 'Kentucky', 'AS': 'American Samoa', 'NV': 'Nevada', 'WY': 'Wyoming', 'NA': 'National', 'AL': 'Alabama', 'MD': 'Maryland', 'AK': 'Alaska', 'UT': 'Utah', 'OR': 'Oregon', 'MT': 'Montana', 'IL': 'Illinois', 'TN': 'Tennessee', 'DC': 'District of Columbia', 'VT': 'Vermont', 'ID': 'Idaho', 'AR': 'Arkansas', 'ME': 'Maine', 'WA': 'Washington', 'HI': 'Hawaii', 'WI': 'Wisconsin', 'MI': 'Michigan', 'IN': 'Indiana', 'NJ': 'New Jersey', 'AZ': 'Arizona', 'GU': 'Guam', 'MS': 'Mississippi', 'PR': 'Puerto Rico', 'NC': 'North Carolina', 'TX': 'Texas', 'SD': 'South Dakota', 'MP': 'Northern Mariana Islands', 'IA': 'Iowa', 'MO': 'Missouri', 'CT': 'Connecticut', 'WV': 'West Virginia', 'SC': 'South Carolina', 'LA': 'Louisiana', 'KS': 'Kansas', 'NY': 'New York', 'NE': 'Nebraska', 'OK': 'Oklahoma', 'FL': 'Florida', 'CA': 'California', 'CO': 'Colorado', 'PA': 'Pennsylvania', 'DE': 'Delaware', 'NM': 'New Mexico', 'RI': 'Rhode Island', 'MN': 'Minnesota', 'VI': 'Virgin Islands', 'NH': 'New Hampshire', 'MA': 'Massachusetts', 'GA': 'Georgia', 'ND': 'North Dakota', 'VA': 'Virginia'}

In [3]:
# Question 1
def get_list_of_university_towns():
    '''Returns a DataFrame of towns and the states they are in from the 
    university_towns.txt list. The format of the DataFrame should be:
    DataFrame( [ ["Michigan", "Ann Arbor"], ["Michigan", "Yipsilanti"] ], 
    columns=["State", "RegionName"]  )
    
    The following cleaning needs to be done:

    1. For "State", removing characters from "[" to the end.
    2. For "RegionName", when applicable, removing every character from " (" to the end.
    3. Depending on how you read the data, you may need to remove newline character '\n'. '''
    
    data = pd.read_table('university_towns.txt', header = None)
    data.rename(columns={0:'State'}, inplace=True)
    data['RegionName'] = data['State']
    data['Test'] = np.nan
    
    for i in range(567):
        line = data.loc[i,'State']
        if line[-5:-1] == 'edit':
            data.loc[i,'Test'] = line
    data = data.fillna(method='ffill', axis=0)
    
    data['State'] = data['Test']
    data = data.drop('Test', axis=1)
    data = data[data['State'] != data['RegionName']]

    data['State'] = data['State'].str.extract('(^[a-zA-Z,.\-\s\:\"]+)', expand=False).str.strip()
    data['RegionName'] = data['RegionName'].str.extract('(^[a-zA-Z,.\-\s\:\"\–]+)', expand=False).str.strip()
    
    data = data.reset_index()
    data = data.drop('index', axis=1)
    data = data.set_index('State')
    data = data.reset_index()

    return data

get_list_of_university_towns()

             State                    RegionName
0          Alabama                        Auburn
1          Alabama                      Florence
2          Alabama                  Jacksonville
3          Alabama                    Livingston
4          Alabama                    Montevallo
5          Alabama                          Troy
6          Alabama                    Tuscaloosa
7          Alabama                      Tuskegee
8           Alaska                     Fairbanks
9          Arizona                     Flagstaff
10         Arizona                         Tempe
11         Arizona                        Tucson
12        Arkansas                   Arkadelphia
13        Arkansas                        Conway
14        Arkansas                  Fayetteville
15        Arkansas                     Jonesboro
16        Arkansas                      Magnolia
17        Arkansas                    Monticello
18        Arkansas                  Russellville
19        Arkansas                        Searcy
20      California                        Angwin
21      California                        Arcata
22      California                      Berkeley
23      California                         Chico
24      California                     Claremont
25      California                        Cotati
26      California                         Davis
27      California                        Irvine
28      California                    Isla Vista
29      California  University Park, Los Angeles
..             ...                           ...
487       Virginia                          Wise
488       Virginia                    Chesapeake
489     Washington                    Bellingham
490     Washington                        Cheney
491     Washington                    Ellensburg
492     Washington                       Pullman
493     Washington  University District, Seattle
494  West Virginia                        Athens
495  West Virginia                    Buckhannon
496  West Virginia                      Fairmont
497  West Virginia                     Glenville
498  West Virginia                    Huntington
499  West Virginia                    Montgomery
500  West Virginia                    Morgantown
501  West Virginia                 Shepherdstown
502  West Virginia                  West Liberty
503      Wisconsin                      Appleton
504      Wisconsin                    Eau Claire
505      Wisconsin                     Green Bay
506      Wisconsin                     La Crosse
507      Wisconsin                       Madison
508      Wisconsin                     Menomonie
509      Wisconsin                     Milwaukee
510      Wisconsin                       Oshkosh
511      Wisconsin                   Platteville
512      Wisconsin                   River Falls
513      Wisconsin                 Stevens Point
514      Wisconsin                      Waukesha
515      Wisconsin                    Whitewater
516        Wyoming                       Laramie

[517 rows x 2 columns]

In [4]:
# Question 1 Checker
import re
# list of unique states
stateStr = """
Ohio, Kentucky, American Samoa, Nevada, Wyoming
,National, Alabama, Maryland, Alaska, Utah
,Oregon, Montana, Illinois, Tennessee, District of Columbia
,Vermont, Idaho, Arkansas, Maine, Washington
,Hawaii, Wisconsin, Michigan, Indiana, New Jersey
,Arizona, Guam, Mississippi, Puerto Rico, North Carolina
,Texas, South Dakota, Northern Mariana Islands, Iowa, Missouri
,Connecticut, West Virginia, South Carolina, Louisiana, Kansas
,New York, Nebraska, Oklahoma, Florida, California
,Colorado, Pennsylvania, Delaware, New Mexico, Rhode Island
,Minnesota, Virgin Islands, New Hampshire, Massachusetts, Georgia
,North Dakota, Virginia
"""
#list of regionName entries string length
regNmLenStr = """
06,08,12,10,10,04,10,08,09,09,05,06,11,06,12,09,08,10,12,06,
06,06,08,05,09,06,05,06,10,28,06,06,09,06,08,09,10,35,09,15,
13,10,07,21,08,07,07,07,12,06,14,07,08,16,09,10,11,09,10,06,
11,05,06,09,10,12,06,06,11,07,08,13,07,11,05,06,06,07,10,08,
11,08,13,12,06,04,08,10,08,07,12,05,06,09,07,10,16,10,06,12,
08,07,06,06,06,11,14,11,07,06,06,12,08,10,11,06,10,14,04,11,
18,07,07,08,09,06,13,11,12,10,07,12,07,04,08,09,09,13,08,10,
16,09,10,08,06,08,12,07,11,09,07,09,06,12,06,09,07,10,09,10,
09,06,15,05,10,09,11,12,10,10,09,13,06,09,11,06,11,09,13,37,
06,13,06,09,49,07,11,12,09,11,11,07,12,10,06,06,09,04,09,15,
10,12,05,09,08,09,09,07,14,06,07,16,12,09,07,09,06,32,07,08,
08,06,10,36,09,10,09,06,09,11,09,06,10,07,14,08,07,06,10,09,
05,11,07,06,08,07,05,07,07,04,06,05,09,04,25,06,07,08,05,08,
06,05,11,09,07,07,06,13,09,05,16,05,10,09,08,11,06,06,06,10,
09,07,06,07,10,05,08,07,06,08,06,30,09,07,06,11,07,12,08,09,
16,12,11,08,06,04,10,10,15,05,11,11,09,08,06,04,10,10,07,09,
11,08,26,07,13,05,11,03,08,07,06,05,08,13,10,08,08,08,07,07,
09,05,04,11,11,07,06,10,11,03,04,06,06,08,08,06,10,09,05,11,
07,09,06,12,13,09,10,11,08,07,07,08,09,10,08,10,08,56,07,12,
07,16,08,04,10,10,10,10,07,09,08,09,09,10,07,09,09,09,12,14,
10,29,19,07,11,12,13,13,09,10,12,12,12,08,10,07,10,07,07,08,
08,08,09,10,09,11,09,07,09,10,11,11,10,09,09,12,09,06,08,07,
12,09,07,07,06,06,08,06,15,08,06,06,10,10,10,07,05,10,07,11,
09,12,10,12,04,10,05,05,04,14,07,10,09,07,11,10,10,10,11,15,
09,14,12,09,09,07,12,04,10,10,06,10,07,28,06,10,08,09,10,10,
10,13,12,08,10,09,09,07,09,09,07,11,11,13,08,10,07
"""

df = get_list_of_university_towns()

cols = ["State", "RegionName"]

print('Shape test: ', "Passed" if df.shape ==
      (517, 2) else 'Failed')
print('Index test: ',
      "Passed" if df.index.tolist() == list(range(517))
      else 'Failed')

print('Column test: ',
      "Passed" if df.columns.tolist() == cols else 'Failed')
print('\\n test: ',
      "Failed" if any(df[cols[0]].str.contains(
          '\n')) or any(df[cols[1]].str.contains('\n'))
      else 'Passed')
print('Trailing whitespace test:',
      "Failed" if any(df[cols[0]].str.contains(
          '\s+$')) or any(df[cols[1]].str.contains(
              '\s+$'))
      else 'Passed')
print('"(" test:',
      "Failed" if any(df[cols[0]].str.contains(
          '\(')) or any(df[cols[1]].str.contains(
              '\('))
      else 'Passed')
print('"[" test:',
      "Failed" if any(df[cols[0]].str.contains(
          '\[')) or any(df[cols[1]].str.contains(
              '\]'))
      else 'Passed')

states_vlist = [st.strip() for st in stateStr.split(',')]

mismatchedStates = df[~df['State'].isin(
    states_vlist)].loc[:, 'State'].unique()
print('State test: ', "Passed" if len(
    mismatchedStates) == 0 else "Failed")
if len(mismatchedStates) > 0:
    print()
    print('The following states failed the equality test:')
    print()
    print('\n'.join(mismatchedStates))

df['expected_length'] = [int(s.strip())
                         for s in regNmLenStr.split(',')
                         if s.strip().isdigit()]
regDiff = df[df['RegionName'].str.len() != df['expected_length']].loc[
    :, ['RegionName', 'expected_length']]
regDiff['actual_length'] = regDiff['RegionName'].str.len()
print('RegionName test: ', "Passed" if len(regDiff) ==
      0 else ' \nMismatching regionNames\n {}'.format(regDiff))

Shape test:  Passed
Index test:  Passed
Column test:  Passed
\n test:  Passed
Trailing whitespace test: Passed
"(" test: Passed
"[" test: Passed
State test:  Passed
RegionName test:  Passed

In [5]:
# Question 2
def get_recession_start():
    '''Returns the year and quarter of the recession start time as a 
    string value in a format such as 2005q3'''
    # We only need data starting with 2000q1
    data = pd.read_excel('gdplev.xls', skiprows = 220, usecols=[4, 5], header = None)
    data.rename(columns= {4:'Season', 5:'GDP'}, inplace=True)
    data = (data.reset_index()
                .drop('index', axis=1))
    
    # A recession is defined as starting with two consecutive quarters of GDP decline  
    recessionStart = []
    for i in np.arange(len(data)-2):
            if (data.iloc[i]['GDP'] > data.iloc[i+1]['GDP']) and (data.iloc[i+1]['GDP'] > data.iloc[i+2]['GDP']):
                recessionStart.append(data.iloc[i]['Season'])
                
    return recessionStart[0]

get_recession_start()

'2008q3'

In [6]:
# Question 3
def get_recession_end():
    '''Returns the year and quarter of the recession end time as a 
    string value in a format such as 2005q3'''
    # We only need data starting with 2000q1
    data = pd.read_excel('gdplev.xls', skiprows = 220, usecols=[4, 5], header = None)
    data.rename(columns= {4:'Season', 5:'GDP'}, inplace=True)
    data = (data.reset_index()
                .drop('index', axis=1))
    # Drop all rows before recession start
    recessionStart = get_recession_start()
    indexStart = 0
    for i in np.arange(len(data)):
            if (data.iloc[i]['Season'] == recessionStart):
                indexStart = i
    data = (data.drop(np.arange(indexStart))
                .reset_index()
                .drop('index', axis=1))
    
    # A recession is defined as ending with two consecutive quarters of GDP growth
    recessionEnd = []
    for i in np.arange(len(data)-2):
            if (data.iloc[i]['GDP'] < data.iloc[i+1]['GDP']) and (data.iloc[i+1]['GDP'] < data.iloc[i+2]['GDP']):
                recessionEnd.append(data.iloc[i+2]['Season'])

    return recessionEnd[0]

get_recession_end()

'2009q4'

In [7]:
# Question 4
def get_recession_bottom():
    '''Returns the year and quarter of the recession bottom time as a 
    string value in a format such as 2005q3'''
    # We only need data starting with 2000q1
    data = pd.read_excel('gdplev.xls', skiprows = 220, usecols=[4, 5], header = None)
    data.rename(columns= {4:'Season', 5:'GDP'}, inplace=True)
    data = (data.reset_index()
                .drop('index', axis=1))
    # Drop all rows before recession start
    recessionStart = get_recession_start()
    indexStart = 0
    for i in np.arange(len(data)):
            if (data.iloc[i]['Season'] == recessionStart):
                indexStart = i
    data = (data.drop(np.arange(indexStart))
                .reset_index()
                .drop('index', axis=1))
    
    # Drop all rows after recession ends
    recessionEnd = get_recession_end()
    indexEnd = 0
    for i in np.arange(len(data)):
            if (data.iloc[i]['Season'] == recessionEnd):
                indexEnd = i
    data = (data.drop(np.arange(indexEnd+1,len(data)))
                .reset_index()
                .drop('index', axis=1))
    
    # A recession bottom is the quarter within a recession which had the lowest GDP
    bottom = data.iloc[data['GDP'].idxmin()]
    return bottom['Season']

get_recession_bottom()

'2009q2'

In [37]:
# Question 5
def convert_housing_data_to_quarters():
    '''Converts the housing data to quarters and returns it as mean 
    values in a dataframe. This dataframe should be a dataframe with
    columns for 2000q1 through 2016q3, and should have a multi-index
    in the shape of ["State","RegionName"].
    
    Note: Quarters are defined in the assignment description, they are
    not arbitrary three month periods.
    
    The resulting dataframe should have 67 columns, and 10,730 rows.
    '''
    houses = pd.read_csv('City_Zhvi_AllHomes.csv', usecols = [1, 2, *range(51, 251)])
    houses = houses.reset_index()
    houses = houses.drop(['index'], axis=1)
    
    houses['State'] = houses['State'].map(states)
    houses = (houses.set_index(['State','RegionName'])
                    .sort_index(level=0, axis=0, ascending=True, inplace=False, sort_remaining=True))
    
    # Computing quartely values
    # A quarter is a specific three month period
    # Q1 is January through March, Q2 is April through June, Q3 is July through September, Q4 is October through December
    
    return houses

convert_housing_data_to_quarters()

                            2000-01   2000-02   2000-03   2000-04   2000-05  \
State     RegionName
Alabama   Adamsville        68700.0   69100.0   69300.0   69200.0   69100.0
          Alabaster        121600.0  122300.0  122500.0  122800.0  123200.0
          Albertville       74300.0   74100.0   73500.0   72700.0   72500.0
          Arab              84500.0   83900.0   82900.0   81900.0   81400.0
          Ardmore               NaN       NaN       NaN       NaN       NaN
          Axis                  NaN       NaN       NaN       NaN       NaN
          Baileyton             NaN       NaN       NaN       NaN       NaN
          Bay Minette       82900.0   81700.0   80500.0   79200.0   78200.0
          Bayou La Batre    44000.0   44100.0   44100.0   44200.0   44600.0
          Bessemer              NaN       NaN       NaN       NaN       NaN
          Birmingham        53900.0   54000.0   54200.0   54300.0   54400.0
          Boaz              70900.0   70900.0   70800.0   70400.0   70200.0
          Brent             92500.0   92800.0   93500.0   94400.0   94400.0
          Brighton              NaN       NaN       NaN       NaN       NaN
          Brookwood         92500.0   92200.0   93000.0   94300.0   95000.0
          Buhl              90900.0   90400.0   91100.0   93100.0   94900.0
          Calera           108300.0  109300.0  109200.0  109900.0  110900.0
          Center Point      80800.0   81000.0   81100.0   80900.0   81200.0
          Centreville       95200.0   95000.0   95700.0   96800.0   96700.0
          Chalkville        93900.0   94100.0   94300.0   94300.0   94500.0
          Chancellor            NaN       NaN       NaN       NaN       NaN
          Chelsea          160000.0  161800.0  164400.0  166600.0  167200.0
          Chickasaw         50300.0   51200.0   52100.0   53100.0   53800.0
          Chunchula         79800.0   80200.0   80800.0   81800.0   81800.0
          Citronelle        63900.0   64700.0   65900.0   66700.0   66400.0
          Clay             120400.0  121100.0  121200.0  121400.0  122200.0
          Coden             62300.0   62500.0   63000.0   64100.0   65200.0
          Coker            116400.0  118000.0  119900.0  121300.0  121000.0
          Concord           78800.0   78400.0   78600.0   78500.0   78600.0
          Cottondale       100500.0  100800.0  101200.0  102000.0  102700.0
...                             ...       ...       ...       ...       ...
Wisconsin Vernon           183200.0  183800.0  182600.0  180500.0  178100.0
          Vienna           177100.0  177800.0  179200.0  181200.0  181800.0
          Vinland          117900.0  119600.0  121900.0  124400.0  126600.0
          Wales                 NaN       NaN       NaN       NaN       NaN
          Waterford        122000.0  121000.0  120600.0  119900.0  119200.0
          Waukesha         141400.0  141700.0  140700.0  139700.0  138400.0
          Waunakee         186100.0  187400.0  188700.0  190200.0  191800.0
          Waupun            83700.0   84200.0   84100.0   83900.0   83900.0
          Wausau            68500.0   69800.0   70400.0   70000.0   69200.0
          Wayne                 NaN       NaN       NaN       NaN       NaN
          West Allis        80600.0   80900.0   81300.0   81600.0   81700.0
          Weston            79200.0   79900.0   81400.0   82300.0   82700.0
          Wheatland        128800.0  129500.0  131100.0  131800.0  131800.0
          Whitelaw          94800.0   96100.0   97200.0   98800.0  101200.0
          Williams Bay     127100.0  122600.0  119000.0  116900.0  115400.0
          Wilson           128100.0  129200.0  129800.0  129300.0  129000.0
          Wilson                NaN       NaN       NaN       NaN       NaN
          Wind Lake        125200.0  124000.0  123900.0  123500.0  123400.0
          Wind Point       150800.0  148800.0  148100.0  147400.0  145400.0
          Wisconsin Dells   98300.0  100000.0  101700.0  102600.0  103500.0
          Wolf River        93700.0   95100.0   96700.0   98200.0   99300.0
          Woodruff              NaN       NaN       NaN       NaN       NaN
          Woodville             NaN       NaN       NaN       NaN       NaN
          Yorkville        140400.0  138800.0  138000.0  136500.0  134700.0
Wyoming   Bar Nunn          93400.0   93100.0   92600.0   91000.0   89300.0
          Burns            100900.0  101300.0  102400.0  103600.0  104400.0
          Casper            88400.0   89300.0   90000.0   90100.0   89600.0
          Cheyenne         116000.0  116700.0  117900.0  119200.0  120100.0
          Evansville       128500.0  128100.0  127500.0  127700.0  128600.0
          Pine Bluffs       93900.0   93400.0   93900.0   94900.0   95300.0

                            2000-06   2000-07   2000-08   2000-09   2000-10  \
State     RegionName
Alabama   Adamsville        69200.0   69500.0   69700.0   70200.0   71100.0
          Alabaster        123200.0  123100.0  123100.0  123300.0  123500.0
          Albertville       72600.0   72500.0   72800.0   73200.0   73500.0
          Arab              81400.0   81200.0   81200.0   81600.0   82400.0
          Ardmore               NaN       NaN       NaN       NaN       NaN
          Axis                  NaN       NaN       NaN       NaN       NaN
          Baileyton             NaN       NaN       NaN       NaN       NaN
          Bay Minette       78200.0   78400.0   79100.0   79900.0   80700.0
          Bayou La Batre    44700.0   44600.0   44300.0   43900.0   43900.0
          Bessemer              NaN       NaN       NaN       NaN       NaN
          Birmingham        54500.0   54700.0   55000.0   55200.0   55600.0
          Boaz              70200.0   70100.0   70100.0   70700.0   71000.0
          Brent             94200.0   94800.0   96400.0   97300.0   98100.0
          Brighton              NaN       NaN       NaN       NaN       NaN
          Brookwood         96000.0   97700.0   99100.0   99800.0  100100.0
          Buhl              95800.0   96400.0   96600.0   96500.0   96500.0
          Calera           110300.0  109000.0  107800.0  107200.0  107200.0
          Center Point      81600.0   81700.0   81500.0   81300.0   81700.0
          Centreville       96200.0   96600.0   98000.0   99400.0   99700.0
          Chalkville        94500.0   94500.0   94500.0   94300.0   94300.0
          Chancellor            NaN       NaN       NaN       NaN       NaN
          Chelsea          167300.0  167200.0  167000.0  166500.0  166700.0
          Chickasaw         54100.0   54400.0   54900.0   55500.0   56000.0
          Chunchula         81700.0   82000.0   82300.0   82300.0   82800.0
          Citronelle        66800.0   67900.0   68400.0   67900.0   67900.0
          Clay             123200.0  123900.0  123900.0  124100.0  125300.0
          Coden             65100.0   65400.0   66800.0   68400.0   68700.0
          Coker            120000.0  118900.0  117900.0  117700.0  116900.0
          Concord           79000.0   79500.0   80100.0   80800.0   81700.0
          Cottondale       103200.0  104000.0  104800.0  105500.0  105600.0
...                             ...       ...       ...       ...       ...
Wisconsin Vernon           176000.0  174600.0  174000.0  174300.0  175300.0
          Vienna           181600.0  181500.0  182300.0  183500.0  184900.0
          Vinland          129300.0  132800.0  135700.0  136300.0  136400.0
          Wales                 NaN       NaN       NaN       NaN       NaN
          Waterford        119200.0  119600.0  120100.0  120900.0  121200.0
          Waukesha         137200.0  136700.0  136600.0  136900.0  137900.0
          Waunakee         192300.0  192000.0  192600.0  193400.0  193400.0
          Waupun            84200.0   84300.0   84400.0   84500.0   84700.0
          Wausau            69200.0   70200.0   71300.0   71600.0   70500.0
          Wayne                 NaN       NaN       NaN       NaN       NaN
          West Allis        82500.0   83900.0   84600.0   83700.0   81900.0
          Weston            83100.0   83600.0   84100.0   84800.0   85400.0
          Wheatland        132800.0  134200.0  134900.0  135700.0  136900.0
          Whitelaw         104300.0  106400.0  108200.0  109500.0  112100.0
          Williams Bay     113600.0  111600.0  110400.0  110300.0  110500.0
          Wilson           129800.0  131400.0  132300.0  133600.0  135600.0
          Wilson                NaN       NaN       NaN       NaN       NaN
          Wind Lake        124100.0  124100.0  123700.0  124600.0  125400.0
          Wind Point       143000.0  141400.0  140200.0  141000.0  144100.0
          Wisconsin Dells  104100.0  104400.0  105000.0  105600.0  105300.0
          Wolf River       100500.0  102200.0  104100.0  105100.0  106100.0
          Woodruff              NaN       NaN       NaN       NaN       NaN
          Woodville             NaN       NaN       NaN       NaN       NaN
          Yorkville        133500.0  133400.0  134600.0  137100.0  138900.0
Wyoming   Bar Nunn          88700.0   88400.0   88600.0   89700.0   91100.0
          Burns            105700.0  107000.0  108200.0  109900.0  111700.0
          Casper            89100.0   89000.0   89500.0   90700.0   92100.0
          Cheyenne         120800.0  121000.0  121400.0  122200.0  123000.0
          Evansville       130000.0  130900.0  130600.0  131000.0  132300.0
          Pine Bluffs       95000.0   94100.0   94200.0   95600.0   97200.0

                            ...     2015-11  2015-12  2016-01  2016-02  \
State     RegionName        ...
Alabama   Adamsville        ...       73900    73500    73600    74100
          Alabaster         ...      151800   152400   152800   153400
          Albertville       ...       91600    91500    91400    92000
          Arab              ...      112500   112100   111000   109800
          Ardmore           ...      144200   143100   142200   142500
          Axis              ...      109500   109000   109600   110300
          Baileyton         ...       97200    97400    97200    96600
          Bay Minette       ...      121700   122000   121300   120300
          Bayou La Batre    ...       48900    48600    48700    48700
          Bessemer          ...       59500    59600    59600    59800
          Birmingham        ...       63200    62600    62400    62000
          Boaz              ...       86700    86400    85700    85700
          Brent             ...       96000    95200    94400    94700
          Brighton          ...       45900    45300    44700    44800
          Brookwood         ...      118400   118100   116600   114900
          Buhl              ...      146400   146300   142300   138900
          Calera            ...      128500   128800   129300   129700
          Center Point      ...       80800    81100    81600    82000
          Centreville       ...      101900   102200   103300   103700
          Chalkville        ...      111300   110600   110800   111700
          Chancellor        ...      110000   109700   110900   113200
          Chelsea           ...      208000   208600   209100   209000
          Chickasaw         ...       58500    58400    58100    57700
          Chunchula         ...      123800   123100   122800   122500
          Citronelle        ...       94100    93200    93000    93400
          Clay              ...      141700   142200   142700   143000
          Coden             ...       80500    80300    80700    81200
          Coker             ...      155300   155400   152800   150400
          Concord           ...      111000   112300   112800   112400
          Cottondale        ...      138000   138000   136100   134000
...                         ...         ...      ...      ...      ...
Wisconsin Vernon            ...      263200   263300   262800   263700
          Vienna            ...      282000   281800   281600   284200
          Vinland           ...      182100   182300   182500   183000
          Wales             ...      267600   267600   266900   267800
          Waterford         ...      230200   229800   230300   230400
          Waukesha          ...      190500   190900   190500   190900
          Waunakee          ...      297500   297300   297700   299600
          Waupun            ...      109800   109500   109400   110600
          Wausau            ...       94700    93700    93600    93700
          Wayne             ...      256600   258000   259800   262200
          West Allis        ...       99900   101700   102000   100800
          Weston            ...      138800   139000   139800   140300
          Wheatland         ...      176200   177500   179200   182300
          Whitelaw          ...      117900   118200   117800   117200
          Williams Bay      ...      225700   226600   229100   230700
          Wilson            ...      166200   168300   169700   170400
          Wilson            ...      188600   189300   188800   188600
          Wind Lake         ...      241700   241700   241600   240700
          Wind Point        ...      249400   252000   254000   254100
          Wisconsin Dells   ...      140600   139700   139400   139700
          Wolf River        ...      163200   162100   160200   159300
          Woodruff          ...      165600   163900   162800   162400
          Woodville         ...      182100   183000   183100   182400
          Yorkville         ...      244100   246500   248800   248800
Wyoming   Bar Nunn          ...      211500   211200   211200   210300
          Burns             ...      164100   164500   166800   168500
          Casper            ...      182300   182600   184000   184500
          Cheyenne          ...      190500   191900   193800   194700
          Evansville        ...      303900   306600   308200   309700
          Pine Bluffs       ...      169600   169300   168400   166300

                           2016-03  2016-04  2016-05  2016-06  2016-07  \
State     RegionName
Alabama   Adamsville         74800    75200    74900    74700    74700
          Alabaster         154200   154900   155200   155200   155600
          Albertville        92600    92600    92400    92400    92300
          Arab              109300   109500   110100   110700   111600
          Ardmore           143000   143200   143400   143100   142300
          Axis              110900   111700   112300   112600   112800
          Baileyton          96500    97500    99100   100100   101300
          Bay Minette       119200   118500   118300   118200   118300
          Bayou La Batre     48300    47800    47800    47900    47600
          Bessemer           59900    59700    59900    60000    59900
          Birmingham         61700    61600    61700    61600    61300
          Boaz               86500    87100    87300    87700    88300
          Brent              94200    93200    91500    89400    87900
          Brighton           45600    45500    44400    43400    43700
          Brookwood         114200   113500   111900   110500   109200
          Buhl              138200   137500   135800   133400   130000
          Calera            129900   130000   130000   129800   129600
          Center Point       82500    82800    83000    83300    83800
          Centreville       102700   101500   100400    99000    98400
          Chalkville        113000   113800   114400   115000   115600
          Chancellor        115800   118800   120800   121400   121500
          Chelsea           209500   210500   211500   212200   213500
          Chickasaw          57500    57200    57000    57000    56800
          Chunchula         122200   122500   123400   124100   124300
          Citronelle         93700    93900    94000    94000    93800
          Clay              143400   144000   144500   145000   145600
          Coden              81400    81900    82300    81900    81000
          Coker             149700   149000   147200   145400   144000
          Concord           111800   111500   111700   112600   113600
          Cottondale        133400   133900   134200   134000   133600
...                            ...      ...      ...      ...      ...
Wisconsin Vernon            265500   266900   268400   269200   272000
          Vienna            286600   286100   285500   285800   288100
          Vinland           183900   185100   186400   188000   189400
          Wales             270600   273400   276200   277400   280300
          Waterford         230900   233200   235200   236100   237000
          Waukesha          192000   193200   194200   194500   197000
          Waunakee          300800   301600   303200   304600   306700
          Waupun            112300   112800   112600   112400   112600
          Wausau             94500    95800    96900    97800    98200
          Wayne             263600   264900   266900   269600   271700
          West Allis         99900   100000    97900    95800    95600
          Weston            140400   140900   142100   143700   144700
          Wheatland         185200   187300   189000   190700   193000
          Whitelaw          116700   116800   117400   118000   117800
          Williams Bay      234900   242800   250100   252300   254000
          Wilson            171300   173000   175000   176600   177900
          Wilson            189800   192500   197200   202100   205200
          Wind Lake         240200   242000   244000   245600   247700
          Wind Point        255100   258300   260900   259300   258100
          Wisconsin Dells   140200   140700   140900   141400   142500
          Wolf River        159000   158800   160200   163800   167100
          Woodruff          162400   161900   161600   162400   163700
          Woodville         182400   184000   186700   189300   192000
          Yorkville         247800   250400   255300   259900   264100
Wyoming   Bar Nunn          209100   209000   209000   208500   207700
          Burns             169500   171100   172100   171600   170700
          Casper            184500   184900   185400   185200   184600
          Cheyenne          194800   195500   196400   197600   198800
          Evansville        310400   310200   308800   308600   308800
          Pine Bluffs       165800   166600   164500   160300   158000

                           2016-08
State     RegionName
Alabama   Adamsville         74700
          Alabaster         156100
          Albertville        92100
          Arab              112400
          Ardmore           141600
          Axis              112700
          Baileyton         103100
          Bay Minette       118700
          Bayou La Batre     47200
          Bessemer           59700
          Birmingham         61200
          Boaz               88900
          Brent              87400
          Brighton           44300
          Brookwood         108100
          Buhl              126700
          Calera            129600
          Center Point       84200
          Centreville        98600
          Chalkville        115800
          Chancellor        121500
          Chelsea           214900
          Chickasaw          56400
          Chunchula         124400
          Citronelle         93700
          Clay              146100
          Coden              80100
          Coker             143100
          Concord           114100
          Cottondale        133500
...                            ...
Wisconsin Vernon            276200
          Vienna            291000
          Vinland           190100
          Wales             284500
          Waterford         238200
          Waukesha          201000
          Waunakee          309500
          Waupun            112900
          Wausau             98200
          Wayne             272800
          West Allis         96100
          Weston            144900
          Wheatland         196000
          Whitelaw          117400

In [9]:
# Question 6
def run_ttest():
    '''First creates new data showing the decline or growth of housing prices
    between the recession start and the recession bottom. Then runs a ttest
    comparing the university town values to the non-university towns values, 
    return whether the alternative hypothesis (that the two groups are the same)
    is true or not as well as the p-value of the confidence. 
    
    Return the tuple (different, p, better) where different=True if the t-test is
    True at a p<0.01 (we reject the null hypothesis), or different=False if 
    otherwise (we cannot reject the null hypothesis). The variable p should
    be equal to the exact p value returned from scipy.stats.ttest_ind(). The
    value for better should be either "university town" or "non-university town"
    depending on which has a lower mean price ratio (which is equivilent to a
    reduced market loss).'''
    
    return "ANSWER"